### ISSUE TITLE
Get rid off print&parse config in Akka cluster initializing code

### ISSUE THREAD

**Issue by dmitring** [tatyanayavkina/akka-cluster-test#5]
https://github.com/tatyanayavkina/akka-cluster-test/blob/bc547937f1d159a58c0f6e0d704ab4f32f4aad3e/src/main/scala/com/github/tatyanayavkina/akkaclusterwithsingleton/SingletonActorApp.scala#L23

**Comment by tatyanayavkina** [comment]
Заменяю на 
```scala
val config = ConfigFactory.load()
        .withValue("akka.remote.artery.canonical.port", ConfigValueFactory.fromAnyRef(port))
```

**Comment by dmitring** [comment]
LGTM
